config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  resource :account, only: :show

  resources :transactions, only: %i[create new index]

  # Defines the root path route ("/")
  root "accounts#show"
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  STATUSES = {
    pending: 'pending',
    success: 'success',
    failed: 'failed'
  }.freeze

  belongs_to :sender, class_name: 'Account'
  belongs_to :receiver, class_name: 'Account'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  has_one :account, dependent: :destroy
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  def show
    @account = current_user.account
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Operations::Transactions::Create.call(permitted_params, current_user)

    if @transaction.persisted?
      redirect_to action: :index
    else
      render :new
    end
  end

  private

  def permitted_params
    params.require(:transaction).permit(:receiver_id, :amount)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/views/accounts/show.html.erb
<h1>Balance: <%= @account.balance - @account.blocked_balance %> coins</h1>

<div class="container">
  <%= button_to "Send Money", new_transaction_path, method: :get, class: 'btn btn-primary' %>
</div>

<div class="container">
  <%= button_to "Transactions history", transactions_path, method: :get, class: 'btn btn-primary' %>
</div>

<div class="container">
  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-warning' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/_form.html.erb
<% if @transaction.errors.any? %>
  <% @transaction.errors.messages.each do |attr, message| %>
    <div  class="alert alert-danger">
      <%= message.last %>
    </div>
  <% end %>
<% end %>

<%= form_with model: @transaction do |form| %>
  <%= form.label :receiver_id, 'Account number of receiver',class: 'form-label' %>
  <%= form.text_field :receiver_id, class: 'form-control', required: true %>
  <%= form.label :amount, 'Amount of coins', class: 'form-label' %>
  <%= form.number_field :amount, step: '0.01', class: 'form-control', required: true %>
  <%= form.submit 'Send coins', class: 'btn btn-primary' %>
<% end %>

app/views/transactions/index.html.erb
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Sender</th>
        <th scope="col">Receiver</th>
        <th scope="col">Amount shifted</th>
        <th scope="col">Status</th>
        <th scope="col">Date</th>
      </tr>
    </thead>
    <tbody>
    <% @transactions.each do |transaction| %>>
      <tr>
        <th scope="row"><%= transaction.sender_id %></th>
        <td><%= transaction.receiver_id %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.status %></td>
        <td><%= transaction.created_at.strftime('%d/%m/%y %H:%M:%S') %></td>
      </tr>
    <% end %>>
    </tbody>
  </table>
</div>

<div class="container">
  <%= button_to "Account", account_path, method: :get, class: 'btn btn-primary' %>
</div>

app/views/transactions/new.html.erb
<div class="container">
  <%= render "form" %>
</div>